
WINDOW_TITLE = "Machine learning game"


# Window Coords 
WIN_WIDTH = 1200
WIN_HEIGHT = 800
WIN_CENTER_X = WIN_WIDTH / 2
WIN_CENTER_Y = WIN_HEIGHT / 2

#Dodge Zone Coords
DZ_FACTOR = 0.6
DZ_WIDTH = WIN_WIDTH * DZ_FACTOR
DZ_HEIGHT = WIN_HEIGHT * DZ_FACTOR
DZ_LEFT = WIN_CENTER_X - (DZ_WIDTH / 2)
DZ_RIGHT = WIN_CENTER_X + (DZ_WIDTH / 2)
DZ_TOP = WIN_CENTER_Y + (DZ_HEIGHT / 2)
DZ_BOTTOM = WIN_CENTER_Y - (DZ_HEIGHT / 2)


